<a href="https://colab.research.google.com/github/justwannachill/NM/blob/main/%D0%9B%D0%A01_%D0%A8%D0%B8%D0%BB%D0%BE%D0%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Шилов Данііл
ФІТ 3-15
Варіант 16


In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

1.Створити матрицю 3*3, заповнити її цілими числами від 1 до 5

In [ ]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[4, 4, 3],
       [1, 3, 1],
       [1, 3, 4]])

2. Обчислити визначник матриці

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(23.999999999999993)

3. Знайти добуток всіх елементів матриці

In [ ]:
product = np.prod(matrix)
product

np.int64(1728)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(1728)

4. Знайти суму всіх елементів матриці

In [ ]:
np.sum(matrix)


np.int64(24)

5. Обчислити найбільший, найменший елементи

In [ ]:
np.max(matrix)


np.int64(4)

In [ ]:
np.min(matrix)


np.int64(1)

6. Знайти середнє значення елементів матриці

In [ ]:
np.mean (matrix)

np.float64(2.6666666666666665)

7. Знайти матрицю, що складена з квадратних коренів

In [ ]:
sqrt_matrix = np.sqrt(matrix)
print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[2.         2.         1.73205081]
 [1.         1.73205081 1.        ]
 [1.         1.73205081 2.        ]]


8. Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
print("Сума елементів кожного рядка:")

print(row_sums)


Сума елементів кожного рядка:
[[11]
 [ 5]
 [ 8]]


In [ ]:
matrix.sum(axis=1).reshape(-1, 1)

array([[11],
       [ 5],
       [ 8]])

In [ ]:
x = np.matrix([[1, 2], [4, 3]])
x

matrix([[1, 2],
        [4, 3]])

In [ ]:
x.sum(axis=1)

matrix([[3],
        [7]])

In [ ]:
x.sum(axis=1, dtype='float')

matrix([[3.],
        [7.]])

9. Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням.

In [ ]:
vector = np.random.randint(0, 10, size=25)
vector

array([2, 8, 6, 8, 6, 7, 8, 8, 9, 0, 9, 0, 4, 6, 5, 2, 1, 7, 9, 0, 4, 4,
       5, 2, 4])

In [ ]:

sorted_vector = np.sort(vector) [::-1]
sorted_vector

array([9, 9, 9, 8, 8, 8, 8, 7, 7, 6, 6, 6, 5, 5, 4, 4, 4, 4, 2, 2, 2, 1,
       0, 0, 0])

10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [ ]:
from scipy import stats
mode = stats.mode(vector)
median = np.median(vector)
mean = np.mean(vector)
max_value = np.max(vector)
min_value = np.min(vector)
print("Мода:", mode)
print("Медіана:", median)
print("Середнє:", mean)
print("Максимальне значення:", max_value)
print("Мінімальне значення:", min_value)

Мода: ModeResult(mode=np.int64(4), count=np.int64(4))
Медіана: 5.0
Середнє: 4.96
Максимальне значення: 9
Мінімальне значення: 0


11. Створити дві матриці 4*4, заповнені числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку.

In [ ]:

matrix1= np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[ 2  8  7  8]
 [ 3  1  1  1]
 [ 4  9  9  4]
 [10  8  9  1]]

Матриця 2:
[[ 3  9  7  6]
 [ 3  5  9  4]
 [ 5  3 10  2]
 [ 6  8  5  3]]


In [ ]:

matrix_sum = matrix1 + matrix2
matrix_diff = matrix1- matrix2
matrix_product= matrix1*matrix2
print("\nСума матриць:")
print(matrix_sum)
print("\nРізниця матриць:")
print(matrix_diff)
print("\nПоелементний добуток матриць:")
print(matrix_product)


Сума матриць:
[[ 5 17 14 14]
 [ 6  6 10  5]
 [ 9 12 19  6]
 [16 16 14  4]]

Різниця матриць:
[[-1 -1  0  2]
 [ 0 -4 -8 -3]
 [-1  6 -1  2]
 [ 4  0  4 -2]]

Поелементний добуток матриць:
[[ 6 72 49 48]
 [ 9  5  9  4]
 [20 27 90  8]
 [60 64 45  3]]


12. Задати вектор-рядок, що містить дійсні числа 1.0-8.0. Зробити матрицю 3*3. Помножити на вектор-рядок, що містить числа 0.0-2.0

In [ ]:
x = np.arange(9.)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2= np.arange(3.)
x2

array([0., 1., 2.])

In [ ]:

np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

13. Задати вектор-рядок (числа 1-5). Обчислити вектор в кубі.

In [ ]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.power (x1, 3)

array([  0,   1,   8,  27,  64, 125])

14. Піднести до ступеня

In [ ]:
x2= np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])

1. Задати вектор, що складається з перших п'яти натуральних чисел.

In [ ]:
vector = np.array([1, 2, 3, 4, 5])
vector

array([1, 2, 3, 4, 5])

2. Транспонувати вектор.

In [ ]:
v1= np.matrix([1, 2, 3, 4, 5])
v1

matrix([[1, 2, 3, 4, 5]])

In [ ]:
v2 = v1.T
v2

matrix([[1],
        [2],
        [3],
        [4],
        [5]])

3. Напишіть функцію, яка перевертає вектор у зворотному порядку

In [ ]:
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [ ]:
v[::-1]

array([5, 4, 3, 2, 1])

In [ ]:
v = np.flip(v)

v

array([5, 4, 3, 2, 1])

7. Обчислити середнє значення вектора

In [ ]:
np.mean(v)

np.float64(3.0)

8.Знайти найбільший і найменший елементи вектора

In [ ]:
np.max(v)

np.int64(5)

In [ ]:
np.min(v)

np.int64(1)

9.Обчислити скалярний добуток (dot product) двох векторів

In [ ]:
v1= np.array([1, 2, 3])
v2 = np.array([4, 5, 6])


In [ ]:
v1

array([1, 2, 3])

In [ ]:
v2

array([4, 5, 6])

In [ ]:
np.dot(v1, v2)

np.int64(32)

10. Напишіть функцію, яка нормалізує вектор (зводить до одиничної довжини).

In [ ]:
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)
print(norm)
v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

11. Задайте два вектори. Визначте, чи є вони ортогональними. Підказка: якщо скалярний добуток дорівнює нулю, вектори ортогональні

In [ ]:
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
np.dot(v1, v2)


np.int64(0)

12. Визначити унікальні елементи вектора

In [ ]:
v = np.array([1, 2, 3, 2, 4, 5, 3])
np.unique(v)

array([1, 2, 3, 4, 5])

13. Знайти вектор, що є різницею між двома векторами

In [ ]:
v1= np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(v1-v2)
print(v2-v1)
print(v1 + v2)
print(v2 + v1)
print(v1*v2)
print(v2*v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


14. Перевірити, чи дорівнює довжина вектора 5

In [ ]:

vector= np.array ([1, 2, 3, 4, 5])
length = np.linalg.norm(vector)
length

np.float64(7.416198487095663)

In [ ]:
np.isclose (length, 5)


np.False_

15. Задати матрицю, заповнену випадковими числами

In [ ]:
a = np.random.randint(0, 11, (3, 3))
a

array([[1, 9, 5],
       [5, 4, 5],
       [5, 8, 3]])

16. Обчислити визначник матриці

In [ ]:
np.linalg.det (a)

np.float64(162.00000000000009)

17. Знаходження оберненої матриці

In [ ]:
np.linalg.inv (a)

array([[-0.17283951,  0.08024691,  0.15432099],
       [ 0.0617284 , -0.13580247,  0.12345679],
       [ 0.12345679,  0.22839506, -0.25308642]])

18. Розв'яжіть систему лінійних рівнянь A-x=b, де А матриця коефіцієнтів, в вектор вільних членів.

In [ ]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b= np.array([5, 3, 4])
x= np.linalg.solve(a, b)
print('Вбудована функція', x.round(1))

inv_a= np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1.round(1))

Вбудована функція [0.4 1.8 0.2]
Матричний метод [0.4 1.8 0.2]


20. Транспонування матриці

In [ ]:
print(a.T)
print(b.T)

[[ 1  0 -2]
 [ 3  2  2]
 [-4 -3  5]]
[5 3 4]


In [ ]:
print(np.transpose(a))
print(np.transpose(b))

[[ 1  0 -2]
 [ 3  2  2]
 [-4 -3  5]]
[5 3 4]


21. Перевірка симетричності матриці

In [ ]:
matrix = np.matrix ([[2, 2,2], [2, 2, 2], [2,2,2]])
np.allclose(matrix, matrix.T)

True

22. Обчислення сліду матриці

In [ ]:
np.trace(matrix)

np.int64(6)

23. Сума матриць

In [ ]:
a = np.matrix ([[1, 2], [3, 4]])
b=np.matrix ([[5, 6], [7, 8]])
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


25. Сортування рядків або стовпців матриці

In [ ]:
b=np.matrix ([[5, 3, 4], [2, 3, 5], [3, 2, 3]])
print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [ ]:
a = np.array([[1,4], [3,1]])

print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]
